# Generated by Django 3.2.13 on 2022-06-25 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participant_registry', '0002_auto_20220625_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='reference_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
