# Generated by Django 3.2.13 on 2022-06-25 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participant_registry', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='address',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='reference_number',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
